version: '3.7'
services:
  mysql_db_container:
    image: mysql:latest
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: eaHo34!390Ssvl
      MYSQL_DATABASE: task_tracker
      MYSQL_USER: user
      MYSQL_PASSWORD: xoQu1@}j9P{p
    ports:
      - "3307:3306"
  back_container:
    restart: always
    image: openjdk:11
    volumes:
      - ./jars:/app
    working_dir: /app
    command: java -jar taskTracker-0.0.1-SNAPSHOT.jar
    ports:
      - "8090:8090"
